export const ROLES = {
  ADMIN: "ADMIN",
  STAFF: "STAFF",
};

export const PERMISSIONS = {
  ARTICLE_VIEW: "ARTICLE_VIEW",
  ARTICLE_CREATE: "ARTICLE_CREATE",
  ARTICLE_EDIT: "ARTICLE_EDIT",
  ARTICLE_DELETE: "ARTICLE_DELETE",
  ARTICLE_SUBMIT: "ARTICLE_SUBMIT",
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_EDIT: "PRODUCT_EDIT",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_SUBMIT: "PRODUCT_SUBMIT",
  MEDIA_VIEW: "MEDIA_VIEW",
  MEDIA_UPLOAD: "MEDIA_UPLOAD",
  LEAD_VIEW: "LEAD_VIEW",
  LEAD_UPDATE: "LEAD_UPDATE",
  CONTENT_APPROVE: "CONTENT_APPROVE",
  CONTENT_REJECT: "CONTENT_REJECT",
  CONTENT_PUBLISH: "CONTENT_PUBLISH",
  CATEGORY_MANAGE: "CATEGORY_MANAGE",
  BANNER_MANAGE: "BANNER_MANAGE",
  PARTNER_MANAGE: "PARTNER_MANAGE",
  SITE_SETTINGS_MANAGE: "SITE_SETTINGS_MANAGE",
  USER_MANAGE: "USER_MANAGE",
  AUDIT_VIEW: "AUDIT_VIEW",
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.STAFF]: [
    PERMISSIONS.ARTICLE_VIEW,
    PERMISSIONS.ARTICLE_CREATE,
    PERMISSIONS.ARTICLE_EDIT,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.ARTICLE_SUBMIT,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_SUBMIT,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_UPDATE,
  ],
};

export function hasPermission(role, permission) {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function hasAnyRole(currentRole, allowedRoles) {
  return allowedRoles.includes(currentRole);
}
